[green_agent]
agentbeats_id = "019c0e01-6248-7f41-a72e-d51ee2ddfb99"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[participants]]
name = "agent"
agentbeats_id = ""  
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
domain = "finance_etf"
num_tasks = 3